# General Configuration
FPS = 60

# Leaf Settings
LEAF_W = 128
LEAF_H = 128
TARGET_LEAF_SIZE = 108
LEAF_VARIANTS_COUNT = 8
LEAF_INITIAL_COUNT = 8
LEAF_SPAWN_INTERVAL = 0.85

# Ripple Simulation Parameters
MAX_RIPPLES = 3
RIPPLE_R_CAP = 150.0
RIPPLE_SOUND_VOLUME = 0.45
RIPPLE_LIFE = 1.5
RIPPLE_SPEED = 80.0
RIPPLE_AMP = 7.0
RIPPLE_WAVELENGTH = 38.0
RIPPLE_RING_WIDTH = 60.0
